export const SHUFFLE = 'SHUFFLE';
export const BACCARAT_PLAYER_DRAW = 'BACCARAT_PLAYER_DRAW';
export const BACCARAT_DEALER_DRAW  = 'BACCARAT_DEALER_DRAW';
export const BACCARAT_PLAYER_TOTAL = 'BACCARAT_PLAYER_TOTAL';
export const BACCARAT_DEALER_TOTAL = 'BACCARAT_DEALER_TOTAL';
export const BACCARAT_HANDS_RESET = 'BACCARAT_HANDS RESET';
export const BACCARAT_PLAYER_TURN = 'BACCARAT_PLAYER_TURN';
export const BACCARAT_DEALER_TURN = 'BACCARAT_DEALER_TURN';
