export const SHUFFLE = 'SHUFFLE';
export const PLAYER_DRAW = 'PLAYER_DRAW';
export const DEALER_DRAW  = 'DEALER_DRAW';
export const BACCARAT_PLAYER_TOTAL = 'BACCARAT_PLAYER_TOTAL';
export const BACCARAT_DEALER_TOTAL = 'BACCARAT_DEALER_TOTAL';
export const HANDS_RESET = 'HANDS RESET';
export const BACCARAT_PLAYER_TURN = 'BACCARAT_PLAYER_TURN';
export const BACCARAT_DEALER_TURN = 'BACCARAT_DEALER_TURN';
