export const BACCARAT_SHUFFLE = 'BACCARAT_SHUFFLE';
export const PLAYER_DRAW = 'PLAYER_DRAW';
export const DEALER_DRAW  = 'DEALER_DRAW';
export const BACCARAT_PLAYER_TOTAL = 'BACCARAT_PLAYER_TOTAL';
export const BACCARAT_DEALER_TOTAL = 'BACCARAT_DEALER_TOTAL';
